export const SERVER_RPC_METHODS = new Set([
  'runQuery',
  'aqlQuery',
  'getBudgetMonths',
  'getBudgetMonth',
  'setBudgetAmount',
  'setBudgetCarryover',
  'addTransactions',
  'importTransactions',
  'getTransactions',
  'updateTransaction',
  'deleteTransaction',
  'getAccounts',
  'createAccount',
  'updateAccount',
  'closeAccount',
  'reopenAccount',
  'deleteAccount',
  'getAccountBalance',
  'getCategoryGroups',
  'createCategoryGroup',
  'updateCategoryGroup',
  'deleteCategoryGroup',
  'getCategories',
  'createCategory',
  'updateCategory',
  'deleteCategory',
  'getNote',
  'updateNote',
  'getCommonPayees',
  'getPayees',
  'createPayee',
  'updatePayee',
  'deletePayee',
  'getTags',
  'createTag',
  'updateTag',
  'deleteTag',
  'mergePayees',
  'getRules',
  'getPayeeRules',
  'createRule',
  'updateRule',
  'deleteRule',
  'holdBudgetForNextMonth',
  'resetBudgetHold',
  'createSchedule',
  'updateSchedule',
  'deleteSchedule',
  'getSchedules',
  'getIDByName',
  'getPreferences',
]);

export function assertJsonSafe(value: unknown): unknown {
  const serialized = JSON.stringify(value);
  if (serialized === undefined) {
    throw new Error('response-not-json-safe');
  }
  return JSON.parse(serialized);
}
